WebApplication1/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AuthorController : Controller
    {
        private LibreriaDBEntities db = new LibreriaDBEntities();

        // GET: Author
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        // GET: Author/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Author/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDauthor,Nombre")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Author/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDauthor,Nombre")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Author/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Author/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class BookController : Controller
    {
        private LibreriaDBEntities db = new LibreriaDBEntities();

        // GET: Book
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.Author);
            return View(books.ToList());
        }

        // GET: Book/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            ViewBag.IDautor = new SelectList(db.Authors, "IDauthor", "Nombre");
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Titulo,IDautor")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                    db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDautor = new SelectList(db.Authors, "IDauthor", "Nombre", book.IDautor);
            return View(book);
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDautor = new SelectList(db.Authors, "IDauthor", "Nombre", book.IDautor);
            return View(book);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Titulo,IDautor")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDautor = new SelectList(db.Authors, "IDauthor", "Nombre", book.IDautor);
            return View(book);
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/Inspiration_ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class Inspiration_ProfilesController : Controller
    {
        private LibreriaDBEntities db = new LibreriaDBEntities();

        // GET: Inspiration_Profiles
        public ActionResult Index()
        {
            return View(db.Inspiration_Profiles.ToList());
        }

        // GET: Inspiration_Profiles/Details/5
        /*public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inspiration_Profiles inspiration_Profiles = db.Inspiration_Profiles.Include(ip => ip.Books.Select(b => b.Author).Where(ip => ip.ID == id).FirstOrDefault();
            if (inspiration_Profiles == null)
            {
                return HttpNotFound();
            }
            return View(inspiration_Profiles);
        }*/

        // GET: Inspiration_Profiles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inspiration_Profiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,email")] Inspiration_Profiles inspiration_Profiles)
        {
            if (ModelState.IsValid)
            {
                db.Inspiration_Profiles.Add(inspiration_Profiles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(inspiration_Profiles);
        }

        // GET: Inspiration_Profiles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inspiration_Profiles inspiration_Profiles = db.Inspiration_Profiles.Find(id);
            if (inspiration_Profiles == null)
            {
                return HttpNotFound();
            }
            return View(inspiration_Profiles);
        }

        // POST: Inspiration_Profiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,email")] Inspiration_Profiles inspiration_Profiles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inspiration_Profiles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inspiration_Profiles);
        }

        // GET: Inspiration_Profiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inspiration_Profiles inspiration_Profiles = db.Inspiration_Profiles.Find(id);
            if (inspiration_Profiles == null)
            {
                return HttpNotFound();
            }
            return View(inspiration_Profiles);
        }

        // POST: Inspiration_Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Inspiration_Profiles inspiration_Profiles = db.Inspiration_Profiles.Find(id);
            db.Inspiration_Profiles.Remove(inspiration_Profiles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult GetBooksByInspirationProfiles(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inspiration_Profiles inspiration_Profiles = (from i in db.Inspiration_Profiles
                                                        where i.ID == id
                                                         select i).FirstOrDefault();
           

            if (inspiration_Profiles == null)
            {
                return HttpNotFound();
            }
            return View(inspiration_Profiles);
        }

        /*
                public ActionResult GetBooksByInspirationProfileID(string terminoFiltrado)
                {
                     if (id == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                        }
                        Inspiration_Profiles inspiration_Profiles = db.Inspiration_Profiles.Find(id);
                        if (inspiration_Profiles == null)
                        {
                            return HttpNotFound();
                        }
                        return View(inspiration_Profiles);
                    }

                //FUNCION PARA HACER FILTRADOS!!!!!

                public ActionResult MinuevoAction(string terminoFiltrado)
                {
                    List<Book> libros = db.Books.Where(l => l.Titulo.Contains(terminoFiltrado) || l.Author.Contains(terminoFiltrado)).ToList();

                    return View("Index", libros);


                public ActionResult MinuevoAction(int id)
                {
                    Book libros = db.Books.Where(l => l.ID == id);

                    return View("Index", libros);

               

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inspiration_Profiles inspiration_Profiles = db.Inspiration_Profiles.Include(a => a.Books).Where(a => a.ID == id.Value).ToList();
            if (inspiration_Profiles == null)
            {
                return HttpNotFound();
            }
            return View(inspiration_Profiles); }*/
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
        <link href="~/Content/PopUpsStyles.css" rel="stylesheet" />
    <link href="~/Content/EstiloLayout.css" rel="stylesheet" />
    <link href="~/Content/EstiloPerfiles.css" rel="stylesheet" />
    <link rel="apple-touch-icon" sizes="57x57" href="images/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="images/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="images/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="images/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="images/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="images/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="images/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="images/favicons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="images/favicons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicons/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <!-- favicons -->
    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="//fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script type="text/javascript" src="script/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="script/all-plugins.js"></script>
    <script type="text/javascript" src="script/plugin-active.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="navegador">
        <a class="navbar-brand" href="#">
            <img src="~/Images/plocfondo.jpg" height="80px"/>
        </a>
        <button id="boton-navegador"class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto justify-content-between">
                <li class="nav-item active nav-link">
                    @Html.ActionLink("Inicio", "Index", "Home")
                </li>
                <li class="nav-item nav-link">
                    @Html.ActionLink("Libros", "Index", "Book")
                </li>
                <li class="nav-item nav-link">
                    @Html.ActionLink("Autores", "Index", "Author")
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Perfiles Inspiradores", "Index", "Inspiration_Profiles")
                </li>
                <li class="nav-item nav-link">
                    @Html.ActionLink("Arma tu Perfil!", "Create", "Inspiration_Profiles")
                </li>
                
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn s my-2 my-sm-0" type="submit">Buscar...</button>
            </form>
        </div>
    </nav>
    <div>
            @RenderBody()
                <footer id="Footer">
                    <div class="container">
                        <div class="social-share">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                        <div class="footer-logo-wrap">
                            Inspiration &copy; 2019. Designed by Flor Hollmann</a>
                        </div>
                    </div>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    <script src="~/Scripts/script.js"></script>
</body>
</html>